# User-friendly name of the workflow
name: Composite Action demo

# Triggers
on:
  # Manual trigger
  workflow_dispatch:
    # Inputs configurable when triggering
    inputs:
      who:
        required: false
        description: Who shall we greet?
        type: text
        
# Array of jobs
jobs:
  # Alias of the job
  greetings:
    name: Greetings
    # Type of runner to run the steps within this job
    runs-on: ubuntu-latest
    # Array of steps
    steps:
      # Use public composite action
      - uses: iveylabs/hello-world-composite-action@v2
        name: Composite action
        id: comp-action
        with:
          who-to-greet: ${{ github.event.inputs.who }}
          if: ${{ github.event.inputs != '' }}
          
      
      # Use the output of the composite action to echo a random number
      - run: echo Random number = ${{ steps.comp-action.outputs.random-number }}
        name: Echo random number
        shell: bash
