name: Deploy to Azure with OIDC
on: [push]

permissions:
      id-token: write
      contents: read

env:
  AZURE_WEBAPP_NAME: aspdotnetcorewelcome    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '6.0.x'           # set this to the dot net version to use

      
jobs: 
  build_test_publish:
    name: 'Build, Test, Publish'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
    -  name: Checkout repo code
       uses: actions/checkout@v2
         
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal

    - name: Publish
      run:   dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp' 
    
   
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: myappartifact
        path: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/myapp' 
        
    outputs:
       stagingURL: 'https://aspdotnetcorewelcome-staging'
       prodURL:  'https://aspdotnetcorewelcome'
     
           
  deploy-to-azure-prod:
    if: github.ref == 'refs/heads/main'
    name: 'Deploy Azure Web App - Prod'
    needs: [build_test_publish]
    runs-on: ubuntu-latest
    environment:
     name: Production
     url: '${{ needs.build_test_publish.outputs.prodURL }}.azurewebsites.net/'
    steps:
     - name: Download Build Artifact
       uses: actions/download-artifact@v2
       id: appartifact
       with:
        name: myappartifact
        path: myappartifact
        
     - name: 'Az CLI login'
       uses: azure/login@v1
       with:
         client-id: ${{ secrets.AZURE_CLIENT_ID }}
         tenant-id: ${{ secrets.AZURE_TENANT_ID }}
         subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
     - name: 'Deploy Azure Web App'
       uses: azure/webapps-deploy@v2
       with:
         app-name: ${{ env.AZURE_WEBAPP_NAME }} 
         package: ${{steps.appartifact.outputs.download-path}}
